### ISSUE TITLE
Can Xcode run this project with VOT?

### ISSUE THREAD

**Issue by someonelikeypp** [vojirt/kcf#17]
If I wanna run this project with XCode by c++，how chould I do

there are some question about this:
1. can I run without trax?
2. whether vot must need matlab to run?
3. the file "gen_cpp_cn.m" need to change to c++ file or something else?

thanks for help.

**Comment by vojirt** [comment]
Hi,
you should be able to run this code in any OS given that you have installed all library dependencies, have C++11 compatible compiler and CMake installed.

1) It can run without trax (viz ./kcf_vot part in README file)
2) VOT can run in matlab or in free alternative Octave (ask question in VOT community for "how to")
3) this file was used to convert static data from .mat (w2crs.mat) file to cpp (cn_data.cpp) . It was included for completeness.

**Comment by someonelikeypp** [comment]
thanks a lot.

so we don't need the file "main_trax.cpp" and "main.cpp" if run the ./kcf_vot part, right?

whether we need VOT to generate the file "region.txt" and "images.txt"?

**Comment by someonelikeypp** [comment]
btw, what's the use of "cn_data.cpp"

**Comment by vojirt** [comment]
it for "color names" features which are used by the KCF along with HoG features. They are basically static mapping of RGB values to 10-D feature space which were learnt offline. For further details, you can read the original paper
J. van de Weijer, C. Schmid, J. J. Verbeek, and D. Larlus. "Learning color names for real-world applications." TIP, 18(7):1512–1524, 2009.

**Comment by someonelikeypp** [comment]
i see, thanks a lot
