### ISSUE TITLE
could you tell me the format of how to run?

### ISSUE THREAD

**Issue by daixiongming** [vojirt/kcf#2]
I have complied under Linux, ./kcf_vot  ,but I do not know how to right the format of input file , could you give me some example？Thanks

**Comment by vojirt** [comment]
Hi,
as written in readme file:
the ./kcf_vot use the VOT2014 input/ouput format.
i.e. the binary expect two files in the directory where it is run
      region.txt with initial coordinates of the object in the first frame (either 4 values [top_left_x, top_left_y, width, height] or 8 values of x1,y1,x2,y2,x3,y3,x4,y4 = four corners of bbox)
      images.txt which contains a list of image files with absolute path that are processed one after each other
output is stored in output.txt file in format [top_left_x, top_left_y, width, height] for each image
