### ISSUE TITLE
how to use linear kernel?

### ISSUE THREAD

**Issue by IamMegatron2025** [vojirt/kcf#28]
hello, how to use linear kernel ? can you give some advises?

looking forward your reply.

**Comment by vojirt** [comment]
Hi, 
after you instantiate the tracker class (in one of main files) e.g.  
tracker = KCF_Tracker()
you can set flag 
tracker.m_use_linearkernel=True 
before calling init or tracking functions.
However, the performance when using linear kernel is lower and the speed benefit is negligible (if any, after compiler optimizations).

**Comment by IamMegatron2025** [comment]
@vojirt  thanks for your reply, but why the speed benefit is negligible when using linear kernel? In the paper, the DCF speed is 70% faster that kcf when using hog feature.

**Comment by vojirt** [comment]
I did not say that the speed is lower. The performance is lower in my evaluation and speed gain is not significant to justify the lower tracking quality. Maybe the speed gain is lower in my case because more complex features and more feature channels are used (color names, ...)

**Comment by IamMegatron2025** [comment]
@vojirt  Sorry, I have modified my comments.    thanks for your advises.
