### ISSUE TITLE
is there a way use fftw to speed up the tracking ?

### ISSUE THREAD

**Issue by qq297110281** [vojirt/kcf#30]
great project !!  i just want to know if there is any way to speed up the tracking. running on arm cpu, it cost almost 2 sec per frame.

**Comment by vojirt** [comment]
Hello, I think that best course of action would be time profiling the code on the machine where you are running the code to see what parts should be optimised. From the method perspective, number of features and their extraction takes probably longest (it is my educated guess), so you can try limiting the type of features you used.
