### ISSUE TITLE
how to run????

### ISSUE THREAD

**Issue by daixiongming** [vojirt/kcf#6]
Dear Tomas,
   Many thanks for your sharing about the code, below is my running about "the kcf"
could you give me so advice ？ I have spend 2days , and I also fail to run!
![image](https://cloud.githubusercontent.com/assets/16714280/17799314/4cfe0212-660c-11e6-8135-b0665dd694a2.png)

![image](https://cloud.githubusercontent.com/assets/16714280/17799319/53d5807e-660c-11e6-90a0-41b52c19b86d.png)

![image](https://cloud.githubusercontent.com/assets/16714280/17799321/57349bec-660c-11e6-99e2-837455e1552c.png)

![image](https://cloud.githubusercontent.com/assets/16714280/17799323/5b928226-660c-11e6-8f86-dd010b342049.png)

![image](https://cloud.githubusercontent.com/assets/16714280/17799324/5fed3df2-660c-11e6-872b-f530999dcf2a.png)

![image](https://cloud.githubusercontent.com/assets/16714280/17799325/629b1c9a-660c-11e6-9fd2-3f44002cda27.png)

**Comment by vojirt** [comment]
from the look of the images, the images.txt and region.txt you edited are in different directory (..../kcf-master) than the directory from which you run the kcf binary (..../kcf-master/build_dai). The bug is not in the VOT init, the error messages tell you what your error is.
