### ISSUE TITLE
the problems

### ISSUE THREAD

**Issue by daixiongming** [vojirt/kcf#8]
![image](https://cloud.githubusercontent.com/assets/16714280/17806704/abb5fb58-6638-11e6-86f4-a26535e78fa8.png)

![image](https://cloud.githubusercontent.com/assets/16714280/17806727/c994a0ac-6638-11e6-90d4-3455f4f7e83b.png)

**Comment by vojirt** [comment]
it looks like the image is not loaded correctly. Verify that the image and region is loaded correctly in main function.
